# Generated by Django 5.0.6 on 2024-05-30 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_list', '0002_alter_streamplatform_updated_alter_watchlist_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='watch_list', to='watch_list.streamplatform'),
            preserve_default=False,
        ),
    ]
